const database = require("../database");
const boosts = require("../systems/boosts");
const xp = require("../utils/xp");
const leveling = require("../systems/leveling");
const luck =
    require("../utils/luck");

const quests =
    require("../systems/quests");


// Keep one immutable source of truth for !roll. The countdown is edited by
// the bot once per second, so it never depends on Discord or device clocks.
const ROLL_COOLDOWN_MS =
    30_000;


const ROLL_CLOCK_EMOJI =
    "⏱️";


// Match only the normal clock emoji countdown generated by this command.
const ROLL_COUNTDOWN_PATTERN =
    /⏱️ \*\*Try again in \d+ seconds?\.\.\.\*\*/;


const ROLL_READY_MESSAGE =
    ROLL_CLOCK_EMOJI +
    " **You can Roll now.**";


const ROLL_EDIT_RETRY_DELAY_MS =
    1000;


const ROLL_FINAL_EDIT_RETRY_WINDOW_MS =
    30_000;


const PERMANENT_ROLL_EDIT_ERROR_CODES =
    new Set([
        10003, // Unknown Channel
        10008, // Unknown Message
        50001, // Missing Access
        50013, // Missing Permissions
        50035  // Invalid Form Body
    ]);


// =====================================================
// EASY ROLL CUSTOMIZATION
// =====================================================
//
// All chancePercent values are REAL percentages:
//
// 72    = 72%
// 0.5   = 0.5%
// 0.05  = 0.05%
// 0.001 = 0.001%
//
// IMPORTANT:
// These are the BASE chances before an active
// Luck Boost changes the outcome weights.
//
// Each level table must add up to exactly 100%.
// The bot checks this automatically when it starts.

const ROLL_SETTINGS = {

    cooldownSeconds:
        ROLL_COOLDOWN_MS / 1000,

    chanceTables: {

        // ==========================
        // LEVEL 1-99
        // ==========================

        level1To100: [

            {
                chancePercent: 60.09,
                type: "neutral",
                min: -100,
                max: 100
            },

            {
                chancePercent: 7,
                type: "negative",
                min: -5000,
                max: -101
            },

            {
                chancePercent: 25,
                type: "positive",
                min: 100,
                max: 5000
            },

            {
                chancePercent: 2,
                type: "negative",
                min: -10000,
                max: -5000
            },

            {
                chancePercent: 5,
                type: "positive",
                min: 5000,
                max: 25000
            },

            {
                chancePercent: 0.5,
                type: "positive",
                min: 25000,
                max: 75000
            },

            {
                chancePercent: 0.1,
                type: "positive",
                min: 75000,
                max: 200000
            },

            {
                chancePercent: 0.05,
                type: "positive",
                min: 200000,
                max: 500000
            },

            {
                chancePercent: 0.009,
                type: "positive",
                min: 500000,
                max: 2000000
            },

            {
                chancePercent: 0.250,
                type: "negative",
                min: -100000,
                max: -10000
            },

            {
                chancePercent: 0.001,
                type: "positive",
                min: 2000000,
                max: 10000000
            }

        ],


        // ==========================
        // LEVEL 100+
        // ==========================

        level101Plus: [

            {
                chancePercent: 38.99,
                type: "neutral",
                min: -100,
                max: 100
            },

            {
                chancePercent: 5,
                type: "negative",
                min: -5000,
                max: -101
            },

            {
                chancePercent: 35,
                type: "positive",
                min: 100,
                max: 5000
            },

            {
                chancePercent: 1,
                type: "negative",
                min: -10000,
                max: -5000
            },

            {
                chancePercent: 15,
                type: "positive",
                min: 5000,
                max: 25000
            },

            {
                chancePercent: 4.60,
                type: "positive",
                min: 25000,
                max: 75000
            },

            {
                chancePercent: 0.3,
                type: "positive",
                min: 75000,
                max: 200000
            },

            {
                chancePercent: 0.09,
                type: "positive",
                min: 200000,
                max: 500000
            },

            {
                chancePercent: 0.009,
                type: "positive",
                min: 500000,
                max: 2000000
            },

            {
                chancePercent: 0.005,
                type: "positive",
                min: 2000000,
                max: 10000000
            },

            {
                chancePercent: 0.006,
                type: "negative",
                min: -10000000,
                max: -2000000
            }

        ]

    }

};


function validateRollChanceTable(
    tableName,
    table
){

    if(!Array.isArray(table) || table.length === 0){

        throw new Error(
            `${tableName} must contain at least one roll outcome.`
        );

    }


    const totalPercent =
        table.reduce(
            (total, outcome) =>
                total +
                Number(outcome.chancePercent || 0),
            0
        );


    if(
        Math.abs(totalPercent - 100) >
        0.000001
    ){

        throw new Error(
            `${tableName} chances must total exactly 100%. Current total: ${totalPercent}%`
        );

    }

}


for(
    const [tableName, table] of
    Object.entries(
        ROLL_SETTINGS.chanceTables
    )
){

    validateRollChanceTable(
        tableName,
        table
    );

}


const ROLL_GUARANTEE_THRESHOLD =
    100;


const ROLL_GUARANTEE_MIN_XP =
    500000;


function buildRollGuaranteeFooter(
    rollGuarantee
){

    const progress =
        Math.max(
            0,
            Number(
                rollGuarantee?.progress
            ) || 0
        );


    const threshold =
        Math.max(
            1,
            Number(
                rollGuarantee?.threshold
            ) || ROLL_GUARANTEE_THRESHOLD
        );


    return (
        `\n\n🎯 **100-Roll Guarantee:** ${progress}/${threshold}`
        +
        (
            rollGuarantee?.guaranteed
                ? `\n🎁 **Milestone reached — this roll was guaranteed ${ROLL_GUARANTEE_MIN_XP.toLocaleString()}+ XP!**`
                : ""
        )
    );

}


function buildRollCooldownExtra(
    rollAccess,
    remainingSeconds =
        ROLL_SETTINGS.cooldownSeconds
){

    if(
        rollAccess?.multiRoll
        ||
        rollAccess?.tripleRoll
    ){

        const rollNumber =
            Math.max(
                1,
                Number(
                    rollAccess?.rollNumber
                ) || 1
            );


        const rollCount =
            Math.max(
                1,
                Number(
                    rollAccess?.rollCount
                ) || 3
            );


        const multiText =
            `\n\n🎰 **MULTI ROLL ${rollNumber}/${rollCount}**` +
            (
                rollAccess?.oneShotBurst
                    ? " • one-time quest reward"
                    : ""
            );


        // Only the final automatic roll needs to repeat the
        // cooldown reminder.
        if(!rollAccess?.showCooldown){

            return multiText;

        }


        return (
            multiText +
            "\n" +
            buildRollCountdownLine(
                remainingSeconds
            )
        );

    }


    return (
        "\n\n" +
        buildRollCountdownLine(
            remainingSeconds
        )
    );

}


function getDisplayedCooldownSeconds(
    remainingMs
){

    const remaining =
        Number(
            remainingMs
        );


    if(
        !Number.isFinite(remaining)
        ||
        remaining <= 0
    ){

        return 0;

    }


    return Math.min(
        ROLL_SETTINGS.cooldownSeconds,
        Math.max(
            1,
            Math.ceil(
                remaining / 1000
            )
        )
    );

}


function buildRollCountdownLine(
    seconds
){

    const safeSeconds =
        Math.max(
            0,
            Math.min(
                ROLL_SETTINGS.cooldownSeconds,
                Math.floor(
                    Number(
                        seconds
                    ) || 0
                )
            )
        );


    const secondLabel =
        safeSeconds === 1
            ? "second"
            : "seconds";


    return (
        ROLL_CLOCK_EMOJI +
        " **Try again in " +
        safeSeconds +
        " " +
        secondLabel +
        "...**"
    );

}


function replaceRollCountdown(
    content,
    seconds
){

    return String(
        content
    ).replace(
        ROLL_COUNTDOWN_PATTERN,
        buildRollCountdownLine(
            seconds
        )
    );

}


function replaceRollCountdownWithReady(
    content
){

    return String(
        content
    ).replace(
        ROLL_COUNTDOWN_PATTERN,
        ROLL_READY_MESSAGE
    );

}


function getRollCountdownEndsAt(
    rollAccess,
    remainingMs
){

    const now =
        Date.now();


    const explicitRemaining =
        Number(
            remainingMs
        );


    const storedRemaining =
        Number(
            rollAccess?.cooldownEndsAt
        ) - now;


    const requestedRemaining =
        Number.isFinite(explicitRemaining)
        &&
        explicitRemaining >= 0
            ? explicitRemaining
            : (
                Number.isFinite(storedRemaining)
                &&
                storedRemaining >= 0
                    ? storedRemaining
                    : ROLL_COOLDOWN_MS
            );


    const safeRemaining =
        Math.max(
            0,
            Math.min(
                ROLL_COOLDOWN_MS,
                requestedRemaining
            )
        );


    return (
        now +
        safeRemaining
    );

}


function isPermanentRollEditError(error){

    const code =
        Number(
            error?.code
            ??
            error?.rawError?.code
            ??
            error?.data?.code
        );


    const status =
        Number(
            error?.status
            ??
            error?.statusCode
        );


    return (
        PERMANENT_ROLL_EDIT_ERROR_CODES.has(
            code
        )
        ||
        status === 403
        ||
        status === 404
    );

}


function getRollCountdownScheduleDelay(
    cooldownEndsAt,
    now = Date.now()
){

    const remaining =
        Number(cooldownEndsAt) -
        Number(now);


    if(
        !Number.isFinite(remaining)
        ||
        remaining <= 0
    ){

        return 0;

    }


    const seconds =
        Math.ceil(
            remaining / 1000
        );


    const untilNextSecond =
        remaining -
        (
            seconds - 1
        ) * 1000;


    // Run just after the next displayed-second boundary. Every later delay is
    // recalculated from the absolute deadline, so lag makes the display jump
    // to the correct number instead of permanently slowing the countdown.
    return Math.max(
        25,
        Math.min(
            1100,
            Math.ceil(
                untilNextSecond
            ) + 25
        )
    );

}


function startRollMessageCountdown(
    sentMessage,
    originalContent,
    cooldownEndsAt
){

    if(
        !sentMessage
        ||
        typeof sentMessage.edit !== "function"
        ||
        !ROLL_COUNTDOWN_PATTERN.test(
            String(
                originalContent
            )
        )
    ){

        return null;

    }


    let lastRenderedState =
        getDisplayedCooldownSeconds(
            cooldownEndsAt -
            Date.now()
        );


    let timer =
        null;


    let stopped =
        false;


    const stop = () => {

        stopped =
            true;


        if(timer){

            clearTimeout(
                timer
            );

            timer =
                null;

        }

    };


    let update;


    const schedule = delay => {

        if(stopped){
            return;
        }


        if(timer){

            clearTimeout(
                timer
            );

        }


        timer =
            setTimeout(
                update,
                Math.max(
                    0,
                    Number(delay) || 0
                )
            );


        if(
            typeof timer.unref ===
            "function"
        ){

            timer.unref();

        }

    };


    update = async() => {

        timer =
            null;


        if(stopped){
            return;
        }


        const now =
            Date.now();


        const seconds =
            getDisplayedCooldownSeconds(
                cooldownEndsAt -
                now
            );


        const ready =
            seconds <= 0;


        const nextState =
            ready
                ? "ready"
                : seconds;


        if(nextState === lastRenderedState){

            schedule(
                getRollCountdownScheduleDelay(
                    cooldownEndsAt,
                    now
                )
            );

            return;

        }


        try{

            await sentMessage.edit({
                content:
                    ready
                        ? replaceRollCountdownWithReady(
                            originalContent
                        )
                        : replaceRollCountdown(
                            originalContent,
                            seconds
                        ),
                allowedMentions: {
                    parse: []
                }
            });


            lastRenderedState =
                nextState;


            if(ready){

                stop();
                return;

            }

        }
        catch(error){

            if(
                isPermanentRollEditError(
                    error
                )
                ||
                Date.now() >
                    cooldownEndsAt +
                    ROLL_FINAL_EDIT_RETRY_WINDOW_MS
            ){

                stop();
                return;

            }


            // Rate limits, temporary Discord failures, and network hiccups
            // retry instead of permanently freezing the countdown.
            schedule(
                ROLL_EDIT_RETRY_DELAY_MS
            );

            return;
        }


        schedule(
            getRollCountdownScheduleDelay(
                cooldownEndsAt
            )
        );

    };


    schedule(
        getRollCountdownScheduleDelay(
            cooldownEndsAt
        )
    );


    return {
        stop
    };

}


async function sendMessageWithRollCountdown(
    sendMessage,
    content,
    rollAccess,
    remainingMs
){

    const cooldownEndsAt =
        getRollCountdownEndsAt(
            rollAccess,
            remainingMs
        );


    const seconds =
        getDisplayedCooldownSeconds(
            cooldownEndsAt -
            Date.now()
        );


    const initialContent =
        replaceRollCountdown(
            content,
            seconds
        );


    const sentMessage =
        await sendMessage(
            initialContent
        );


    startRollMessageCountdown(
        sentMessage,
        initialContent,
        cooldownEndsAt
    );


    return sentMessage;

}


function sendRollResultMessage(
    message,
    rollAccess,
    content
){

    return sendMessageWithRollCountdown(
        value =>
            message.channel.send(
                value
            ),
        content,
        rollAccess
    );

}


function sendRollCooldownReply(
    message,
    rollAccess,
    content
){

    return sendMessageWithRollCountdown(
        value =>
            message.reply(
                value
            ),
        content,
        rollAccess,
        rollAccess?.remaining
    );

}


async function syncRollLevel(
    message,
    userID
){

    const levelResult =
        await leveling.syncLevelAndAnnounce(
            message.client,
            message.guild.id,
            userID
        );


    await quests.recordLevelChange(
        message,
        levelResult,
        userID
    );


    return levelResult;

}


async function execute(message, options = {}){


    if(!message.guild)
        return;



    const userID =
        message.author.id;


    const user =
        await database.getUser(
            message.guild.id,
            userID
        );


    const currentLevel =
        xp.getLevel(
            Number(user.xp)
        );


    // The new split is exactly Level 1-99 vs. Level 100+.
    const levelTableName =
        currentLevel >= 100
            ? "level101Plus"
            : "level1To100";


    const rollChanceTable =
        ROLL_SETTINGS.chanceTables[
            levelTableName
        ];


    const activeLuckBoost =
        await luck.getActiveLuckBoost(
            message.member
        );


    const rollLuckProfile =
        luck.getRollLuckProfile(
            activeLuckBoost,
            currentLevel
        );


    // Luck changes the roll odds, never the wait between rolls.
    // Every normal or Multi Roll batch uses exactly 30 seconds.
    const currentRollCooldown =
        ROLL_COOLDOWN_MS;



    // ======================
    // Cooldown
    // ======================

const rollAccess =
    options.rollAccess
    ||
    await quests.useRollCooldown(
        message.guild.id,
        message.author.id,
        currentRollCooldown
    );


if(!rollAccess.allowed){


    const seconds =
        getDisplayedCooldownSeconds(
            rollAccess.remaining
        );


    const messageText =
        buildRollCountdownLine(
            seconds
        );


    return sendRollCooldownReply(
        message,
        rollAccess,
        messageText
    );


}


// ======================
// QUEST MULTI ROLL
// ======================
//
// One typed !roll command now performs the rewarded number of complete,
// independent rolls automatically. Each roll still uses:
// - its own XP result
// - its own Luck calculation
// - its own XP MAX / Luck Boost drop checks
// - its own quest progress
// - its own bonus / Impossible bonus
//
// The cooldown was already consumed once above.
if(
    (
        rollAccess.multiRoll
        ||
        rollAccess.tripleRoll
    )
    &&
    !options.skipCooldown
){

    const rollCount =
        Math.max(
            1,
            Number(
                rollAccess.rollCount
            ) || 3
        );


    for(
        let rollIndex = 0;
        rollIndex < rollCount;
        rollIndex++
    ){

        await execute(
            message,
            {
                skipCooldown: true,

                rollAccess: {
                    ...rollAccess,

                    rollNumber:
                        rollIndex + 1,

                    rollCount,

                    showCooldown:
                        rollIndex ===
                        rollCount - 1
                }
            }
        );

    }


    return;

}





// ======================
// ROLL WITH LUCK
// ======================

const luckResult =
    await luck.rollWithLuck(
        message.member,
        rollChanceTable,
        levelTableName,
        rollLuckProfile
    );


let rolledXP =
    luckResult.rolledXP;


const guaranteedRoll =
    await quests.consumeGuaranteedRoll(
        message.guild.id,
        userID
    );


if(guaranteedRoll === "daily_25k_75k"){

    rolledXP =
        Math.max(
            rolledXP,
            Math.floor(
                Math.random() * 50001
            ) + 25000
        );

}
else if(guaranteedRoll === "impossible"){

    rolledXP =
        Math.max(
            rolledXP,
            Math.floor(
                Math.random() * 1500001
            ) + 500000
        );

}
else if(
    guaranteedRoll?.type === "minimum"
){

    rolledXP =
        luck.rollGuaranteedMinimumWithLuck(
            rolledXP,
            Number(
                guaranteedRoll.minXP
            ) || 0,
            rollChanceTable,
            levelTableName,
            rollLuckProfile
        );

}


// Each actual result advances the meter, including every individual result
// in Multi Roll. The counter is stored in PostgreSQL, so restarts do not
// erase progress and concurrent rolls cannot lose an increment.
const rollGuarantee =
    await database.advanceRollGuarantee(
        message.guild.id,
        userID,
        ROLL_GUARANTEE_THRESHOLD
    );


if(rollGuarantee.guaranteed){

    rolledXP =
        luck.rollGuaranteedMinimumWithLuck(
            rolledXP,
            ROLL_GUARANTEE_MIN_XP,
            rollChanceTable,
            levelTableName,
            rollLuckProfile
        );

}


// This is the Luck Boost used
// during the current roll.
//
// A Luck Boost won from this roll
// starts affecting future rolls.

const usedLuckBoost =
    luckResult.profile;


    // ======================
    // GIVE XP
    // ======================


await database.addXP(

    message.guild.id,

    userID,

    rolledXP

);


await quests.recordEvent(
    message,
    "roll_count",
    1
);


await quests.recordEvent(
    message,
    "roll_xp",
    Math.max(
        0,
        rolledXP
    )
);


// "Roll more than X XP" quests use ONE individual roll only.
// Multi Roll calls this same single-roll path once per result, so
// smaller automatic rolls can never combine into one single-roll quest.
await quests.recordEvent(
    message,
    "single_roll_xp",
    Math.max(
        0,
        rolledXP
    )
);


await quests.recordEvent(
    message,
    "earn_xp",
    Math.max(
        0,
        rolledXP
    )
);


// Track roll XP for boosts
await database.addBoostActivity(

    message.guild.id,

    userID,

    Math.max(0, rolledXP)

);

// ======================
// RANDOM XP BOOST DROP
// ======================
// Each real roll—including each result inside Multi Roll—uses the exact
// mutually-exclusive roll drop chances from systems/boosts.js.

const xpBoostDropMessage =
    await boosts.tryXPBoostDropInline(
        message,
        "roll",
        "!roll"
    );

// ======================
// LUCK BOOST REWARD
// ======================
//
// This happens before any result message,
// so every roll can potentially award:
//
// - XP
// - one possible XP Boost tier
// - Luck Boost

const wonLuckBoost =
    await luck.tryLuckBoostDrop(
        message.member
    );


const xpBoostDropExtra =
    xpBoostDropMessage
        ? `\n${xpBoostDropMessage}`
        : "";


const guaranteedRollExtra =
    guaranteedRoll === "daily_25k_75k"
        ? "\nQuest reward used: guaranteed 25,000–75,000 XP roll."
        : guaranteedRoll === "impossible"
            ? "\nQuest reward used: guaranteed Impossible Roll."
            : guaranteedRoll?.type === "minimum"
                ? `\nQuest reward used: guaranteed ${Number(guaranteedRoll.minXP).toLocaleString()}+ XP roll.`
                : "";


const megaRollExtra =
    luckResult.megaRoll
        ? (
            `\n💎 **MEGA LUCK ROLL!** ` +
            `Your active Luck Boost hit its **${Number(
                luckResult.megaRollChancePercent
            ).toLocaleString("en-US", {
                maximumFractionDigits: 6
            })}%** chance for **10,000,001–50,000,000 XP**.`
        )
        : "";


const rollExtras =
    luck.buildRollExtras(
        message,
        usedLuckBoost,
        wonLuckBoost
    )
    + xpBoostDropExtra
    + guaranteedRollExtra
    + megaRollExtra
    + buildRollCooldownExtra(
        rollAccess
    );


const rollGuaranteeFooter =
    buildRollGuaranteeFooter(
        rollGuarantee
    );







// ======================
// Impossible Roll
// ======================

if(rolledXP >= 500000){

const bonus =
    Math.floor(
        Math.random() * 1250001
    ) + 750000;

await database.addXP(

    message.guild.id,

    userID,

    bonus

);


await database.addBoostActivity(

    message.guild.id,

    userID,

    bonus

);


await quests.recordEvent(
    message,
    "earn_xp",
    bonus
);


await syncRollLevel(
    message,
    userID
);

    return sendRollResultMessage(
        message,
        rollAccess,

`🌠 **THE UNIVERSE FALLS SILENT.**

${message.author} rolled **+${rolledXP.toLocaleString()} XP!**${rollExtras}

*Time itself seems to stop.*

*Mizuki simply stares at the glowing number.*

*"...."*

*"You're... unreal."*

*Without saying another word, she rushes toward ${message.author}, wraps both arms around them and refuses to let go.*

*"I... I don't ever want to forget this moment..."*

*After several long seconds she finally lets go, cheeks glowing bright red.*

*"Congratulations... my luckiest person."*

💖 **Mizuki secretly rewarded you with +${bonus.toLocaleString()} XP!**

✨ **The universe itself acknowledged your existence.**${rollGuaranteeFooter}`

    );

}





// ======================
// Legendary Lucky Bonus
// ======================

if(rolledXP >= 200000){

const bonus =
    Math.floor(
        Math.random() * 350001
    ) + 150000;

await database.addXP(

    message.guild.id,

    userID,

    bonus

);


await database.addBoostActivity(

    message.guild.id,

    userID,

    bonus

);


await quests.recordEvent(
    message,
    "earn_xp",
    bonus
);


await syncRollLevel(
    message,
    userID
);

    return sendRollResultMessage(
        message,
        rollAccess,

`✨ ${message.author} rolled **+${rolledXP.toLocaleString()} XP!**${rollExtras}

*Mizuki stares in complete disbelief.*

*"That's impossible..."*

*Golden sparkles begin swirling around both of you.*

*Mizuki suddenly laughs, throws herself into your arms, and hugs you as tightly as she can.*

*"Hehe... maybe you're my lucky charm after all~"*

💖 **Mizuki secretly rewarded you with +${bonus.toLocaleString()} XP!**${rollGuaranteeFooter}`

    );

}


// ======================
// 75k - 200k
// ======================

if(rolledXP >= 75000){

    const bonus =
    Math.floor(
        Math.random() * 75001
    ) + 50000;

    await database.addXP(
        message.guild.id,
        userID,
        bonus
    );

    await database.addBoostActivity(
        message.guild.id,
        userID,
        bonus
    );

    await quests.recordEvent(
        message,
        "earn_xp",
        bonus
    );

await syncRollLevel(
    message,
    userID
);

    return sendRollResultMessage(
        message,
        rollAccess,

`🌌 ${message.author} rolled **+${rolledXP.toLocaleString()} XP!**${rollExtras}

*The air itself seems to shimmer.*

*Mizuki slowly lands beside you, completely speechless.*

*"I... I don't even know what to say..."*

*She gently holds both of your hands.*

*"Promise me you'll stay by my side, okay?"*

*She blushes, kisses both cheeks, then quietly flies away.*

💖 **Mizuki secretly rewarded you with +${bonus.toLocaleString()} XP!**${rollGuaranteeFooter}`

    );

}


// ======================
// 25k - 75k
// ======================

if(rolledXP >= 25000){

    const bonus =
    Math.floor(
        Math.random() * 40001
    ) + 10000;

    await database.addXP(
        message.guild.id,
        userID,
        bonus
    );

    await database.addBoostActivity(
        message.guild.id,
        userID,
        bonus
    );

    await quests.recordEvent(
        message,
        "earn_xp",
        bonus
    );

await syncRollLevel(
    message,
    userID
);

    return sendRollResultMessage(
        message,
        rollAccess,

`🌟 ${message.author} rolled **+${rolledXP.toLocaleString()} XP!**${rollExtras}

*Mizuki almost drops out of the sky from pure shock.*

*"N-No way..."*

*She circles around you several times, unable to stop smiling.*

*"I've never seen luck like this..."*

*She hugs you tightly, spins you around laughing, then kisses your forehead.*

💖 **Mizuki secretly rewarded you with +${bonus.toLocaleString()} XP!**${rollGuaranteeFooter}`

    );

}

// ======================
// Lucky Roll Bonus
// ======================

if(rolledXP >= 1000){

const bonus =
    Math.floor(
        Math.random() * 501
    ) + 500;

await database.addXP(

    message.guild.id,

    userID,

    bonus

);


await database.addBoostActivity(

    message.guild.id,

    userID,

    bonus

);


await quests.recordEvent(
    message,
    "earn_xp",
    bonus
);


await syncRollLevel(
    message,
    userID
);

    return sendRollResultMessage(
        message,
        rollAccess,

`🎲 ${message.author} rolled **+${rolledXP.toLocaleString()} XP!**${rollExtras}

*Mizuki's eyes widen for a second before a warm smile appears.*

*"Hehe~ You're stronger than I thought..."*

*She floats closer, gently pats your head before wrapping her arms around you in a quick hug.*

*"Don't stop now... I want to see how far you can go."*

💖 **Mizuki secretly rewarded you with +${bonus} XP!**${rollGuaranteeFooter}`

    );

}


// ======================
// Kiss
// ======================

if(rolledXP > 100){

const bonus =
    Math.floor(
        Math.random() * 451
    ) + 50;

await database.addXP(

    message.guild.id,

    userID,

    bonus

);

await database.addBoostActivity(

    message.guild.id,

    userID,

    bonus

);

await quests.recordEvent(
    message,
    "earn_xp",
    bonus
);

await syncRollLevel(
    message,
    userID
);


return sendRollResultMessage(
    message,
    rollAccess,

`🎲 ${message.author} rolled **+${rolledXP.toLocaleString()} XP!**${rollExtras}

*Mizuki keeps watching ${message.author} with a smile and a slight blush, then flies over and whispers quietly...*

*"Woow... you're my lucky boy/girl~..."*

*She gently kisses ${message.author}'s cheek before flying away.*

💖 The kiss gave you **+${bonus} XP** as a bonus!${rollGuaranteeFooter}`

);

}



// ======================
// UPDATE LEVEL
// ======================

await syncRollLevel(
    message,
    userID
);



// ======================
// Normal messages
// ======================

if(rolledXP >= 0){

    return sendRollResultMessage(
        message,
        rollAccess,

`🎲 ${message.author} rolled **+${rolledXP.toLocaleString()} XP! Lucky! 🍀**${rollExtras}${rollGuaranteeFooter}`

    );

}


return sendRollResultMessage(
    message,
    rollAccess,

`🎲 ${message.author} rolled **${rolledXP.toLocaleString()} XP!** Better luck next time... 💀${rollExtras}${rollGuaranteeFooter}`

);


}



module.exports = {

    execute,

    ROLL_COOLDOWN_MS,

    buildRollCooldownExtra,

    getDisplayedCooldownSeconds,

    buildRollCountdownLine,

    replaceRollCountdown,

    replaceRollCountdownWithReady,

    getRollCountdownEndsAt,

    isPermanentRollEditError,

    getRollCountdownScheduleDelay,

    startRollMessageCountdown,

    sendMessageWithRollCountdown,

    ROLL_READY_MESSAGE

};
