const database = require("../database");
const boosts = require("../systems/boosts");
const xp = require("../utils/xp");
const leveling = require("../systems/leveling");
const luck =
    require("../utils/luck");
const trolls =
    require("../systems/trolls");

const quests =
    require("../systems/quests");


// Keep one immutable source of truth for !roll. The countdown is edited by
// the bot once per second, so it never depends on Discord or device clocks.
const ROLL_COOLDOWN_MS =
    30_000;


const ROLL_CLOCK_EMOJI =
    "⏱️";


// Match only the normal clock emoji countdown generated by this command.
const ROLL_COUNTDOWN_PATTERN =
    /⏱️ \*\*Try again in \d+ seconds?\.\.\.\*\*/;


const ROLL_READY_MESSAGE =
    ROLL_CLOCK_EMOJI +
    " **You can Roll now.**";


const ROLL_EDIT_RETRY_DELAY_MS =
    1000;


const ROLL_FINAL_EDIT_RETRY_WINDOW_MS =
    30_000;


const ROLL_REVEAL_FRAME_DELAY_MS =
    1000;


const ROLL_MESSAGE_MAX_LENGTH =
    1900;


const PERMANENT_ROLL_EDIT_ERROR_CODES =
    new Set([
        10003, // Unknown Channel
        10008, // Unknown Message
        50001, // Missing Access
        50013, // Missing Permissions
        50035  // Invalid Form Body
    ]);


// =====================================================
// EASY ROLL CUSTOMIZATION
// =====================================================
//
// All chancePercent values are REAL percentages:
//
// 72    = 72%
// 0.5   = 0.5%
// 0.05  = 0.05%
// 0.001 = 0.001%
//
// IMPORTANT:
// These are the BASE chances before an active
// Luck Boost changes the outcome weights.
//
// The universal base table must add up to exactly 100%.
// The bot checks this automatically when it starts.

const ROLL_SETTINGS = {

    cooldownSeconds:
        ROLL_COOLDOWN_MS / 1000,

    chanceTables: {

        // Every user begins with this same table. Rolling upgrades create a
        // personal normalized copy without mutating these base chances.

        base: [

            {
                chancePercent: 60.089824,
                type: "neutral",
                min: -100,
                max: 100
            },

            {
                chancePercent: 7,
                type: "negative",
                min: -5000,
                max: -101
            },

            {
                chancePercent: 25,
                type: "positive",
                min: 100,
                max: 5000
            },

            {
                chancePercent: 2,
                type: "negative",
                min: -10000,
                max: -5000
            },

            {
                chancePercent: 5,
                type: "positive",
                min: 5000,
                max: 25000
            },

            {
                chancePercent: 0.5,
                type: "positive",
                min: 25000,
                max: 75000
            },

            {
                chancePercent: 0.1,
                type: "positive",
                min: 75000,
                max: 200000
            },

            {
                chancePercent: 0.05,
                type: "positive",
                min: 200000,
                max: 500000
            },

            {
                chancePercent: 0.009,
                type: "positive",
                min: 500000,
                max: 2000000
            },

            {
                chancePercent: 0.250,
                type: "negative",
                min: -100000,
                max: -10000
            },

            {
                chancePercent: 0.001,
                type: "positive",
                min: 2000000,
                max: 10000000
            },

            {
                chancePercent: 0.0001,
                type: "positive",
                min: 10000001,
                max: 30000000
            },

            {
                chancePercent: 0.00005,
                type: "positive",
                min: 30000001,
                max: 50000000
            },

            {
                chancePercent: 0.00002,
                type: "positive",
                min: 50000001,
                max: 100000000
            },

            {
                chancePercent: 0.000005,
                type: "positive",
                min: 100000001,
                max: 250000000
            },

            {
                chancePercent: 0.000001,
                type: "positive",
                min: 250000001,
                max: 500000000
            }

        ]

    }

};


function rollGuaranteedNegative(
    chanceTable = ROLL_SETTINGS.chanceTables.base,
    random = Math.random
){

    const negativeOutcomes = chanceTable.filter(outcome =>
        outcome.type === "negative"
        && Number(outcome.max) < 0
    );

    const totalWeight = negativeOutcomes.reduce(
        (sum, outcome) =>
            sum + Math.max(0, Number(outcome.chancePercent) || 0),
        0
    );

    let cursor = random() * totalWeight;
    let selected = negativeOutcomes[negativeOutcomes.length - 1];

    for(const outcome of negativeOutcomes){
        cursor -= Math.max(0, Number(outcome.chancePercent) || 0);
        if(cursor < 0){
            selected = outcome;
            break;
        }
    }

    const min = Math.ceil(Math.min(selected.min, selected.max));
    const max = Math.floor(Math.max(selected.min, selected.max));

    return Math.floor(random() * (max - min + 1)) + min;

}


function validateRollChanceTable(
    tableName,
    table
){

    if(!Array.isArray(table) || table.length === 0){

        throw new Error(
            `${tableName} must contain at least one roll outcome.`
        );

    }


    const totalPercent =
        table.reduce(
            (total, outcome) =>
                total +
                Number(outcome.chancePercent || 0),
            0
        );


    if(
        Math.abs(totalPercent - 100) >
        0.000001
    ){

        throw new Error(
            `${tableName} chances must total exactly 100%. Current total: ${totalPercent}%`
        );

    }

}


for(
    const [tableName, table] of
    Object.entries(
        ROLL_SETTINGS.chanceTables
    )
){

    validateRollChanceTable(
        tableName,
        table
    );

}


// Upgrade weights are normalized into a fresh chance table, so every level
// still totals exactly 100% and the shared base table never gets mutated.
function getRollingUpgradeChanceTable(
    baseTable,
    rollingLevel
){

    return luck.getRollingUpgradeChanceTable(
        baseTable,
        rollingLevel
    );

}


const ROLL_GUARANTEE_THRESHOLD =
    100;


const ROLL_GUARANTEE_MIN_XP =
    500000;


// The 100-roll milestone has its own capped Luck tables. This prevents
// permanent Boost and Rolling upgrades from multiplying an already-guaranteed
// result into an uncontrolled high-range chance. No Luck through MAX still
// favor 500,000–10,000,000 XP, while the rare three-minute Ω boost is
// intentionally allowed to be extremely powerful.
const ROLL_GUARANTEE_XP_RANGES = [
    { type: "positive", min: 500000, max: 2000000 },
    { type: "positive", min: 2000001, max: 10000000 },
    { type: "positive", min: 10000001, max: 30000000 },
    { type: "positive", min: 30000001, max: 50000000 },
    { type: "positive", min: 50000001, max: 100000000 },
    { type: "positive", min: 100000001, max: 250000000 },
    { type: "positive", min: 250000001, max: 1500000000 }
];


// Array positions match ROLL_GUARANTEE_XP_RANGES above.
// 0 = no boost, 1 = Luck I, 2 = Luck II, 3 = Luck III,
// 4 = Luck MAX, 5 = Luck Ω.
const ROLL_GUARANTEE_CHANCES_BY_LUCK_ORDER = {
    0: [75, 23, 1.4, 0.3, 0.15, 0.1, 0.05],
    1: [70, 26.5, 2.4, 0.5, 0.25, 0.25, 0.1],
    2: [65, 30, 3.4, 0.8, 0.4, 0.3, 0.1],
    3: [58, 34.5, 5, 1.2, 0.6, 0.5, 0.2],
    4: [50, 40, 6, 1.5, 0.8, 1.2, 0.5],
    5: [10, 20, 25, 18, 12, 10, 5]
};


const ROLL_GUARANTEE_CHANCE_TABLES =
    Object.fromEntries(
        Object.entries(
            ROLL_GUARANTEE_CHANCES_BY_LUCK_ORDER
        ).map(([luckOrder, chances]) => [
            luckOrder,
            ROLL_GUARANTEE_XP_RANGES.map(
                (range, index) => ({
                    ...range,
                    chancePercent:
                        chances[index]
                })
            )
        ])
    );


for(
    const [luckOrder, table] of
    Object.entries(
        ROLL_GUARANTEE_CHANCE_TABLES
    )
){
    validateRollChanceTable(
        `100-roll guarantee Luck order ${luckOrder}`,
        table
    );
}


// Retained as the no-boost source table for compatibility with any existing
// tests or utilities that import this constant directly.
const ROLL_GUARANTEE_CHANCE_TABLE =
    ROLL_GUARANTEE_CHANCE_TABLES[0];


function getRollGuaranteeLuckOrder(
    rollLuckProfile
){
    return Math.max(
        0,
        Math.min(
            5,
            Math.floor(
                Number(
                    rollLuckProfile?.order
                ) || 0
            )
        )
    );
}


function getRollGuaranteeChanceTable(
    rollLuckProfile
){
    return (
        ROLL_GUARANTEE_CHANCE_TABLES[
            getRollGuaranteeLuckOrder(
                rollLuckProfile
            )
        ]
        || ROLL_GUARANTEE_CHANCE_TABLE
    );
}


function buildRollGuaranteeFooter(
    rollGuarantee
){

    const progress =
        Math.max(
            0,
            Number(
                rollGuarantee?.progress
            ) || 0
        );


    const threshold =
        Math.max(
            1,
            Number(
                rollGuarantee?.threshold
            ) || ROLL_GUARANTEE_THRESHOLD
        );


    return (
        `\n\n🎯 100 Rolls Guarantee: ${progress}/${threshold}`
        +
        (
            rollGuarantee?.guaranteed
                ? `\n🎁 **Milestone reached — ${ROLL_GUARANTEE_MIN_XP.toLocaleString()} XP minimum, with greatly boosted odds for more than 2,000,000 XP!**`
                : ""
        )
    );

}


function buildRollCooldownExtra(
    rollAccess,
    remainingSeconds =
        ROLL_SETTINGS.cooldownSeconds
){

    if(
        rollAccess?.multiRoll
        ||
        rollAccess?.tripleRoll
    ){

        const rollNumber =
            Math.max(
                1,
                Number(
                    rollAccess?.rollNumber
                ) || 1
            );


        const rollCount =
            Math.max(
                1,
                Number(
                    rollAccess?.rollCount
                ) || 3
            );


        const multiText =
            `\n\n🎰 **MULTI ROLL ${rollNumber}/${rollCount}**` +
            (
                rollAccess?.oneShotBurst
                    ? " • one-time quest reward"
                    : ""
            );


        // Only the final automatic roll needs to repeat the
        // cooldown reminder.
        if(!rollAccess?.showCooldown){

            return multiText;

        }


        return (
            multiText +
            "\n" +
            buildRollCountdownLine(
                remainingSeconds
            )
        );

    }


    return (
        "\n\n" +
        buildRollCountdownLine(
            remainingSeconds
        )
    );

}


function getDisplayedCooldownSeconds(
    remainingMs
){

    const remaining =
        Number(
            remainingMs
        );


    if(
        !Number.isFinite(remaining)
        ||
        remaining <= 0
    ){

        return 0;

    }


    return Math.min(
        ROLL_SETTINGS.cooldownSeconds,
        Math.max(
            1,
            Math.ceil(
                remaining / 1000
            )
        )
    );

}


function buildRollCountdownLine(
    seconds
){

    const safeSeconds =
        Math.max(
            0,
            Math.min(
                ROLL_SETTINGS.cooldownSeconds,
                Math.floor(
                    Number(
                        seconds
                    ) || 0
                )
            )
        );


    const secondLabel =
        safeSeconds === 1
            ? "second"
            : "seconds";


    return (
        ROLL_CLOCK_EMOJI +
        " **Try again in " +
        safeSeconds +
        " " +
        secondLabel +
        "...**"
    );

}


function replaceRollCountdown(
    content,
    seconds
){

    return String(
        content
    ).replace(
        ROLL_COUNTDOWN_PATTERN,
        buildRollCountdownLine(
            seconds
        )
    );

}


function replaceRollCountdownWithReady(
    content
){

    return String(
        content
    ).replace(
        ROLL_COUNTDOWN_PATTERN,
        ROLL_READY_MESSAGE
    );

}


function getRollCountdownEndsAt(
    rollAccess,
    remainingMs
){

    const now =
        Date.now();


    const explicitRemaining =
        Number(
            remainingMs
        );


    const storedRemaining =
        Number(
            rollAccess?.cooldownEndsAt
        ) - now;


    const hasStoredDeadline =
        Number.isFinite(
            Number(
                rollAccess?.cooldownEndsAt
            )
        )
        &&
        Number(
            rollAccess?.cooldownEndsAt
        ) > 0;


    const requestedRemaining =
        Number.isFinite(explicitRemaining)
        &&
        explicitRemaining >= 0
            ? explicitRemaining
            : (
                hasStoredDeadline
                    ? Math.max(
                        0,
                        storedRemaining
                    )
                    : ROLL_COOLDOWN_MS
            );


    const safeRemaining =
        Math.max(
            0,
            Math.min(
                ROLL_COOLDOWN_MS,
                requestedRemaining
            )
        );


    return (
        now +
        safeRemaining
    );

}


function isPermanentRollEditError(error){

    const code =
        Number(
            error?.code
            ??
            error?.rawError?.code
            ??
            error?.data?.code
        );


    const status =
        Number(
            error?.status
            ??
            error?.statusCode
        );


    return (
        PERMANENT_ROLL_EDIT_ERROR_CODES.has(
            code
        )
        ||
        status === 403
        ||
        status === 404
    );

}


function getRollCountdownScheduleDelay(
    cooldownEndsAt,
    now = Date.now()
){

    const remaining =
        Number(cooldownEndsAt) -
        Number(now);


    if(
        !Number.isFinite(remaining)
        ||
        remaining <= 0
    ){

        return 0;

    }


    const seconds =
        Math.ceil(
            remaining / 1000
        );


    const untilNextSecond =
        remaining -
        (
            seconds - 1
        ) * 1000;


    // Run just after the next displayed-second boundary. Every later delay is
    // recalculated from the absolute deadline, so lag makes the display jump
    // to the correct number instead of permanently slowing the countdown.
    return Math.max(
        25,
        Math.min(
            1100,
            Math.ceil(
                untilNextSecond
            ) + 25
        )
    );

}


function startRollMessageCountdown(
    sentMessage,
    originalContent,
    cooldownEndsAt
){

    if(
        !sentMessage
        ||
        typeof sentMessage.edit !== "function"
        ||
        !ROLL_COUNTDOWN_PATTERN.test(
            String(
                originalContent
            )
        )
    ){

        return null;

    }


    let lastRenderedState =
        getDisplayedCooldownSeconds(
            cooldownEndsAt -
            Date.now()
        );


    let timer =
        null;


    let stopped =
        false;


    const stop = () => {

        stopped =
            true;


        if(timer){

            clearTimeout(
                timer
            );

            timer =
                null;

        }

    };


    let update;


    const schedule = delay => {

        if(stopped){
            return;
        }


        if(timer){

            clearTimeout(
                timer
            );

        }


        timer =
            setTimeout(
                update,
                Math.max(
                    0,
                    Number(delay) || 0
                )
            );


        if(
            typeof timer.unref ===
            "function"
        ){

            timer.unref();

        }

    };


    update = async() => {

        timer =
            null;


        if(stopped){
            return;
        }


        const now =
            Date.now();


        const seconds =
            getDisplayedCooldownSeconds(
                cooldownEndsAt -
                now
            );


        const ready =
            seconds <= 0;


        const nextState =
            ready
                ? "ready"
                : seconds;


        if(nextState === lastRenderedState){

            schedule(
                getRollCountdownScheduleDelay(
                    cooldownEndsAt,
                    now
                )
            );

            return;

        }


        try{

            await sentMessage.edit({
                content:
                    ready
                        ? replaceRollCountdownWithReady(
                            originalContent
                        )
                        : replaceRollCountdown(
                            originalContent,
                            seconds
                        ),
                allowedMentions: {
                    parse: []
                }
            });


            lastRenderedState =
                nextState;


            if(ready){

                stop();
                return;

            }

        }
        catch(error){

            if(
                isPermanentRollEditError(
                    error
                )
                ||
                Date.now() >
                    cooldownEndsAt +
                    ROLL_FINAL_EDIT_RETRY_WINDOW_MS
            ){

                stop();
                return;

            }


            // Rate limits, temporary Discord failures, and network hiccups
            // retry instead of permanently freezing the countdown.
            schedule(
                ROLL_EDIT_RETRY_DELAY_MS
            );

            return;
        }


        schedule(
            getRollCountdownScheduleDelay(
                cooldownEndsAt
            )
        );

    };


    schedule(
        getRollCountdownScheduleDelay(
            cooldownEndsAt
        )
    );


    return {
        stop
    };

}


async function sendMessageWithRollCountdown(
    sendMessage,
    content,
    rollAccess,
    remainingMs
){

    const cooldownEndsAt =
        getRollCountdownEndsAt(
            rollAccess,
            remainingMs
        );


    const seconds =
        getDisplayedCooldownSeconds(
            cooldownEndsAt -
            Date.now()
        );


    const initialContent =
        seconds <= 0
            ? replaceRollCountdownWithReady(
                content
            )
            : replaceRollCountdown(
                content,
                seconds
            );


    const sentMessage =
        await sendMessage(
            initialContent
        );


    startRollMessageCountdown(
        sentMessage,
        initialContent,
        cooldownEndsAt
    );


    return sentMessage;

}


function getCustomEmoji(
    guild,
    name,
    fallback
){

    const emoji =
        guild?.emojis?.cache?.find?.(
            entry => entry.name === name
        );


    return emoji
        ? emoji.toString()
        : fallback;

}


function getRollEmojis(guild){

    return {
        roll:
            getCustomEmoji(
                guild,
                "roll",
                "🎲"
            ),

        halfGoldenRoll:
            getCustomEmoji(
                guild,
                "half_golden_roll",
                "✨"
            ),

        goldenRoll:
            getCustomEmoji(
                guild,
                "golden_roll",
                "🌠"
            ),

        mythicRoll:
            getCustomEmoji(
                guild,
                "mythic_roll",
                "🌃"
            ),

        rainbowRoll:
            getCustomEmoji(
                guild,
                "rainbow_roll",
                "🌈"
            ),

        giftHeart:
            getCustomEmoji(
                guild,
                "gift_heart",
                "💝"
            ),

        halfGoldenHeart:
            getCustomEmoji(
                guild,
                "half_golden_heart",
                "💖"
            ),

        goldenHeart:
            getCustomEmoji(
                guild,
                "golden_heart",
                "💛"
            ),

        mythicHeart:
            getCustomEmoji(
                guild,
                "mythic_heart",
                "💜"
            ),

        inevitableGalaxy:
            getCustomEmoji(
                guild,
                "inevitable_galaxy",
                "🌌"
            )
    };

}


function getRollRevealEmojiSequence(
    rolledXP,
    guild
){

    const safeXP =
        Number(rolledXP) || 0;


    if(safeXP <= 25000){
        return [];
    }


    const emojis =
        getRollEmojis(guild);

    const sequence = [
        emojis.roll
    ];


    if(safeXP > 100000){
        sequence.push(
            emojis.halfGoldenRoll
        );
    }


    if(safeXP > 500000){
        sequence.push(
            emojis.goldenRoll
        );
    }


    if(safeXP > 5000000){
        sequence.push(
            emojis.mythicRoll
        );
    }


    return sequence;

}


function waitForRollReveal(milliseconds){

    return new Promise(
        resolve =>
            setTimeout(
                resolve,
                Math.max(
                    0,
                    Number(milliseconds) || 0
                )
            )
    );

}


function buildRollRevealText(
    emoji,
    dotCount = 3
){

    const safeDotCount =
        Math.max(
            1,
            Math.min(
                3,
                Math.floor(
                    Number(dotCount) || 1
                )
            )
        );


    return (
        `${emoji} Rolling` +
        ".".repeat(
            safeDotCount
        )
    );

}


async function playRollReveal(
    message,
    rolledXP,
    wait = waitForRollReveal
){

    const emojiSequence =
        getRollRevealEmojiSequence(
            rolledXP,
            message.guild
        );


    if(emojiSequence.length === 0){
        return null;
    }


    const waitFunction =
        typeof wait === "function"
            ? wait
            : waitForRollReveal;

    let revealMessage = null;


    try{

        revealMessage =
            await message.reply({
                content:
                    buildRollRevealText(
                        emojiSequence[0],
                        3
                    ),

                allowedMentions: {
                    repliedUser: false,
                    parse: []
                }
            });


        if(
            !revealMessage
            ||
            typeof revealMessage.edit !==
                "function"
        ){

            return revealMessage;

        }


        for(
            let emojiIndex = 0;
            emojiIndex < emojiSequence.length;
            emojiIndex++
        ){

            const emoji =
                emojiSequence[emojiIndex];


            if(emojiIndex > 0){

                await revealMessage.edit({
                    content:
                        buildRollRevealText(
                            emoji,
                            3
                        ),
                    allowedMentions: {
                        parse: []
                    }
                });

            }


            await waitFunction(
                ROLL_REVEAL_FRAME_DELAY_MS
            );


            for(
                let dotCount = 1;
                dotCount <= 3;
                dotCount++
            ){

                await revealMessage.edit({
                    content:
                        buildRollRevealText(
                            emoji,
                            dotCount
                        ),
                    allowedMentions: {
                        parse: []
                    }
                });


                await waitFunction(
                    ROLL_REVEAL_FRAME_DELAY_MS
                );

            }

        }

    }
    catch(_error){

        // A missing permission, a deleted loading message, or a temporary
        // Discord edit failure must never prevent the real roll result.

    }
    finally{

        if(
            revealMessage
            &&
            typeof revealMessage.delete ===
                "function"
        ){

            try{
                await revealMessage.delete();
            }
            catch(_error){
                // The final roll result still needs to be sent.
            }

        }

    }


    return revealMessage;

}


function splitLongMessage(
    content,
    maxLength = ROLL_MESSAGE_MAX_LENGTH
){

    const paragraphs =
        String(content || "")
            .split("\n\n");

    const chunks = [];
    let chunk = "";


    function pushPiece(piece){

        const candidate =
            chunk
                ? `${chunk}\n\n${piece}`
                : piece;


        if(candidate.length <= maxLength){
            chunk = candidate;
            return;
        }


        if(chunk){
            chunks.push(chunk);
            chunk = "";
        }


        if(piece.length <= maxLength){
            chunk = piece;
            return;
        }


        for(
            let start = 0;
            start < piece.length;
            start += maxLength
        ){

            const slice =
                piece.slice(
                    start,
                    start + maxLength
                );


            if(slice.length === maxLength){
                chunks.push(slice);
            }
            else{
                chunk = slice;
            }

        }

    }


    for(const paragraph of paragraphs){
        pushPiece(paragraph);
    }


    if(chunk){
        chunks.push(chunk);
    }


    return chunks;

}


async function sendRollResultMessage(
    message,
    rollAccess,
    content
){

    const cooldownEndsAt =
        getRollCountdownEndsAt(
            rollAccess
        );

    const seconds =
        getDisplayedCooldownSeconds(
            cooldownEndsAt -
            Date.now()
        );

    const preparedContent =
        seconds <= 0
            ? replaceRollCountdownWithReady(
                content
            )
            : replaceRollCountdown(
                content,
                seconds
            );

    const chunks =
        splitLongMessage(
            preparedContent
        );

    let lastSentMessage = null;


    for(
        let index = 0;
        index < chunks.length;
        index++
    ){

        const chunk =
            chunks[index];


        lastSentMessage =
            await message.channel.send({
                content: chunk,

                allowedMentions: {
                    users:
                        index === 0
                            ? [message.author.id]
                            : [],
                    roles: [],
                    repliedUser: false
                }
            });


        if(
            ROLL_COUNTDOWN_PATTERN.test(
                chunk
            )
        ){

            startRollMessageCountdown(
                lastSentMessage,
                chunk,
                cooldownEndsAt
            );

        }

    }


    return lastSentMessage;

}


function getRollBonusPercentRange(
    rolledXP
){

    const safeXP =
        Number(rolledXP) || 0;


    if(safeXP >= 100000000){
        return {
            minimumPercentLess: 5,
            maximumPercentLess: 10
        };
    }


    if(safeXP > 5000000){
        return {
            minimumPercentLess: 15,
            maximumPercentLess: 50
        };
    }


    if(safeXP > 500000){
        return {
            minimumPercentLess: 15,
            maximumPercentLess: 50
        };
    }


    if(safeXP > 100000){
        return {
            minimumPercentLess: 10,
            maximumPercentLess: 30
        };
    }


    if(safeXP > 25000){
        return {
            minimumPercentLess: 15,
            maximumPercentLess: 50
        };
    }


    return null;

}


function rollPercentageLessBonus(
    rolledXP,
    minimumPercentLess,
    maximumPercentLess,
    random = Math.random
){

    const safeXP =
        Math.max(
            0,
            Math.floor(
                Number(rolledXP) || 0
            )
        );

    const safeMinimumPercentLess =
        Math.max(
            0,
            Math.min(
                100,
                Number(minimumPercentLess) || 0
            )
        );

    const safeMaximumPercentLess =
        Math.max(
            safeMinimumPercentLess,
            Math.min(
                100,
                Number(maximumPercentLess) || 0
            )
        );

    const minimumBonus =
        Math.floor(
            safeXP *
            (
                100 -
                safeMaximumPercentLess
            ) /
            100
        );

    const maximumBonus =
        Math.floor(
            safeXP *
            (
                100 -
                safeMinimumPercentLess
            ) /
            100
        );


    if(maximumBonus <= minimumBonus){
        return minimumBonus;
    }


    const position =
        Math.max(
            0,
            Math.min(
                0.999999999999,
                Number(random()) || 0
            )
        );


    return (
        minimumBonus +
        Math.floor(
            position *
            (
                maximumBonus -
                minimumBonus +
                1
            )
        )
    );

}


function buildPositiveRollDialogue({
    message,
    rolledXP,
    bonusXP = 0,
    rollCooldownExtra = "",
    rollContextExtras = "",
    rollGuaranteeFooter = ""
}){

    const author =
        message.author;

    const emojis =
        getRollEmojis(
            message.guild
        );

    const formattedRolledXP =
        Number(rolledXP)
            .toLocaleString();

    const formattedBonusXP =
        Number(bonusXP)
            .toLocaleString();

    const resultExtras =
        rollCooldownExtra +
        rollContextExtras;


    if(rolledXP >= 100000000){

        return `${emojis.rainbowRoll} ${author} ROLLED A JACKPOT 🎰 **[${formattedRolledXP} XP]**${resultExtras}

### The future?

*While beyondborder_08386 & ${author} keep working on the teleportation gun, after a few hours of working on it, beyondborder_08386 calmly says:*

"It's almost finished..."

*While they are still creating it, the crew behind them are quite quiet...

That's because gorjezz is sleeping on the couch, thezdrink is sitting on an armchair, still in anguish and still thinking that they failed—which they did...

Zero & kdc came back from obtaining some well-earned power, and then they went to their bedroom to sleep.

But... Kape is hovering in the air, meditating, his head twitching violently as if he's looking at the future and all the different outcomes of the incoming conflict.

beyondborder_08386 looks back and sees this, then glances at ${author}.*

"Uh... ${author}...? What is Kape doing?" *beyondborder_08386 asks while ${author} says "idk" with a gesture.*

*${author} & beyondborder_08386 slowly walk toward Kape before Kape drops to the ground, breathing heavily and, most importantly... looking shocked...

beyondborder_08386 blinks at Kape before crouching beside him.*

"You good, Kape?" *beyondborder_08386 asks before ${author} adds:*

"Hey... what were you doing?" *${author} asks curiously.*

*Kape looks at them, still in slight shock, before answering:*

"I looked into the near future, at all of the possible outcomes of the incoming conflict..."

*beyondborder_08386 & ${author} keep looking at him in shock, while gorjezz wakes up and listens as well.

gorjezz then decides to ask:*

"How many did you see, Kape...?" *Kape looks at gorjezz and, still in shock, answers:*

"273,302,067..." *Kape answers.*

*beyondborder_08386 & ${author} look at each other before looking back at Kape.*

"How many did we win...?" *beyondborder_08386 asks slightly coldly.*

*Kape gulps before answering:*

"Twelve..."

*Kape says as beyondborder_08386, ${author} & gorjezz watch in pure shock.*

**${emojis.rainbowRoll} The shocked future made ${author} gain some bonus power by ${formattedBonusXP} XP!**${rollGuaranteeFooter}`;

    }


    if(rolledXP > 5000000){

        return `${emojis.mythicRoll} ${author} rolled **+${formattedRolledXP} XP!** 🌃${resultExtras}

### The Great Ruler

*When Kape was selected and chosen to be the next administrator, Kape needed a weapon...

You see, every administrator has their own weapon, so Kape not having one meant he wasn't truly an administrator yet...

One day, after Kape had already heard the news about being chosen as the next administrator, a really powerful unknown person wearing a black hood that hid his face approached him...

Kape was wandering around the streets before a dark portal appeared in front of him and the unknown person reappeared once more...*

"You'll have to come with me, Kape..." *the unknown person said.*

*Kape had no option but to agree and follow him. They walked through the portal and entered a strange white parallel universe, with every object floating around them. They walked on slightly transparent ground, as if they were far away from every living planet—at the edge of the universe...

As they walked, Kape decided to ask questions...*

"So... uh... Since you know my name... can I at least know your name, sir...?"

*The powerful unknown person looked at Kape while walking, then looked ahead.*

"Call me... Frampto."

*Frampto simply said. Kape nodded and remembered that name for the future...

They reached someone sitting upon a throne. Kape sensed his immense power. It was unlike anything Kape had ever felt before—something truly unfathomable...*

"Thy Great Ruler, I bring the Chosen One..." *Frampto said as he got on his knees, showing respect for The Great Ruler.*

*Meanwhile, Kape was still standing there...

The Great Ruler, seated upon the throne, looked at Kape as a red glint shone from his pupils...

Then The Great Ruler stood up and looked down at Kape.*

"As you have been informed, you have been chosen to be the new administrator..."

*The Great Ruler paused.*

"Are you sure you're ready to bring peace and ensure that the people are safe with your new, inevitable abilities...?"

*Kape kept looking at The Great Ruler and answered:*

"Yes..."

*The Great Ruler watched Kape for a second before speaking.*

"Great..."

*The Great Ruler paused before snapping his fingers, spawning an Infinity Gauntlet in his hands. He continued to speak:*

"Please accept my unfathomable gift, made especially for you..."

*Kape smiled slightly and took the Gauntlet from The Great Ruler.

Before equipping it, Kape bowed to The Great Ruler as a sign of respect...

Then Kape finally equipped it and felt the bonus, unfathomable power coursing through his veins...*

"Alright, and that's the end of the story..." *Kape said to the crew while they were sitting on the couch.*

*Some had even slept through the story: gorjezz nodded while saying "wow," thezdrink acknowledged it by saying "nices," beyondborder_08386 listened carefully and coldly, and Mrnoob simply blinked at Kape before asking:*

"And uh... What's The Great Ruler's name?"

*Kape blinked back at Mrnoob and answered:*

"Uh... I-I... don't know that yet..."

*Mrnoob just blinked back at Kape while ${author}, shadow067972, and kdc were sleeping and snoring loudly...*

**${emojis.mythicHeart} The story made ${author} gain some bonus power by ${formattedBonusXP} XP!**${rollGuaranteeFooter}`;

    }


    if(rolledXP > 500000){

        return `${emojis.goldenRoll} ${author} rolled **+${formattedRolledXP} XP!** 🌠${resultExtras}

### ${author} VS beyondborder_08386

*beyondborder_08386 was walking toward the crew's house until he saw ${author} running up to him from the house.*

"Hey! Let's bet our power on rolling the dice!" *${author} said energetically.*

*beyondborder_08386 blinked at ${author} and coldly kept staring.

beyondborder_08386 could definitely feel that ${author} was stronger—as if ${author} had already won every bet and taken power from Mrhacker and Kape...*

"Alright... I guess..."

*beyondborder_08386 rolled first with two dice. He needed a total of 10. He shook them in his hands before rolling and got...

The numbers 5 and 4. beyondborder_08386 blinked at the dice and started getting suspicious because he had thrown them perfectly...

It was ${author}'s turn. ${author} needed exactly 9 with both dice combined. ${author} rolled and got...

The numbers 6 and 3. ${author} won once again...

beyondborder_08386 stared suspiciously while ${author} simply smiled back at him.

beyondborder_08386 sighed, raised his hand, and spared some of his power, making ${author} even stronger...

${author} powered up, a dark green aura surrounding them, but then beyondborder_08386 noticed something: when ${author} had rolled the dice, there had been a strange, faint green glow around them...*

"You're cheating..."

*beyondborder_08386 stated it as a fact, not a question. ${author} looked at him with slightly widened eyes...*

"Uh... no... what are you talking about, heh...?"

*beyondborder_08386 stepped closer to ${author} and, without saying anything, kicked them in the gut, making ${author} gasp and slide backward.*

"That's what you get for cheating..." *beyondborder_08386 said as ${author} groaned.*

*${author} gritted their teeth and charged at beyondborder_08386, trying to punch him directly in the face...

But beyondborder_08386 saw it coming and simply moved his head aside, dodging successfully...

Then ${author} tried kicking beyondborder_08386 in the torso, but he blocked it, sending ${author} sliding back slightly...

${author} tried another punch. beyondborder_08386 grabbed ${author}'s hand, stopped the incoming attack, punched ${author} in the face several times, and threw them away...*

*${author} tried a sweep kick from the ground, but beyondborder_08386 blocked it with his leg. ${author} then jumped into the air and attempted a dragon kick. beyondborder_08386 dodged the first kick by ducking, but the second kick struck him in the face...

beyondborder_08386 grew colder, calculated ${author}'s next attack, dodged it easily, punched ${author} in the gut several times, and kicked them away...

${author} was knocked back badly and fell to their knees, bleeding slightly...*

"Even with your new stolen power... you lack technique..." *beyondborder_08386 said coldly while looking down at ${author}.*

*beyondborder_08386 simply turned around and walked away...

${author} gritted their teeth and swore they would make beyondborder_08386 pay...*

**${emojis.goldenHeart} The fight made ${author} gain some bonus power by ${formattedBonusXP} XP!**${rollGuaranteeFooter}`;

    }


    if(rolledXP > 100000){

        return `${emojis.halfGoldenRoll} ${author} rolled **+${formattedRolledXP} XP!** ${emojis.inevitableGalaxy}${resultExtras}

*Kape was sitting on the crew's couch with gorjezz before seeing ${author} arrive...*

"Sup..." *Kape said with a neutral tone.*

"Hellooo-..." *gorjezz said sweetly.*

*${author} placed something on the table and answered:*

"Hi..." *${author} simply said before sitting beside them on the couch.*

*gorjezz blinked at the objects ${author} had placed on the table.*

"What's this...?" *gorjezz asked curiously.*

*${author} smiled and explained:*

"These are dice..." *${author} paused.*

"We're going to gambleeeeeeeee our power..."

*Kape and gorjezz blinked at each other before Kape spoke:*

"Okay, buddy..."

*They started playing. Kape needed to roll 11 or more with two dice combined. Kape rolled the two dice and got the numbers 5 and 4—which was not more than 11. Kape sighed before it became gorjezz's turn.

gorjezz needed to roll 7 or more with two dice combined. gorjezz rolled and got the numbers 5 and 2—right on the dot. That meant she didn't have to give her power to anyone...

Now it was ${author}'s turn. ${author} needed to roll exactly 12 with two dice combined. ${author} rolled and actually got double sixes...

Kape sighed, slightly annoyed, and raised his Gauntlet toward ${author}. Using the Stones, Kape gave ${author} a huge temporary boost in power...*

**${emojis.halfGoldenHeart} Kape accidentally rewarded you more as a bonus with ${formattedBonusXP} XP!**${rollGuaranteeFooter}`;

    }


    if(rolledXP > 25000){

        return `${emojis.roll} ${author} rolled **+${formattedRolledXP} XP!** ✨${resultExtras}

*Mrnoob was wandering outside beside the crew's house when he saw thezdrink and ${author} walking nearby. Mrnoob quickly approached them...*

"Hey guys!" *Mrnoob said as he waved at them.*

*${author} and thezdrink approached Mrnoob as well.*

"What's up...?" *${author} and thezdrink said at the same time.*

*Mrnoob smiled and said:*

"If you guys roll more XP than me, I'll give you some of my power. But if I win, you guys will give me... 50% of your power..."

*${author} and thezdrink thought about it and agreed. Mrnoob quickly pulled out a die and said:*

"If I roll the number 1, then I win... If you guys roll the number 3, then you win..."

*Mrnoob rolled first and got the number... 2. Mrnoob blinked at the result and handed them the die. ${author} decided to roll because they felt lucky and... actually rolled the number 3.*

"Alright, whatever! I didn't use Luck Boosts like you noobs!" *Mrnoob said as he spared some of his power for both thezdrink and, mainly, ${author}.*

**${emojis.giftHeart} Mrnoob accidentally rewarded you more as a bonus with ${formattedBonusXP} XP!**${rollGuaranteeFooter}`;

    }


    if(rolledXP > 5000){

        return `${emojis.roll} ${author} rolled **+${formattedRolledXP} XP!**${resultExtras}

*Mizuki told ${author} that if they rolled a die and it landed on the number 6, Mizuki would reward them...

If not, Mizuki would punish ${author}... but ${author} actually rolled a 6...

A deal is a deal...*

"Wow, that was just pure luck..." *Mizuki grumbled as she snapped her fingers.*

*Giving ${author} a temporary power boost.*${rollGuaranteeFooter}`;

    }


    return `${emojis.roll} ${author} rolled **+${formattedRolledXP} XP!**${resultExtras}${rollGuaranteeFooter}`;

}


function sendRollCooldownReply(
    message,
    rollAccess,
    content
){

    return sendMessageWithRollCountdown(
        value =>
            message.reply(
                value
            ),
        content,
        rollAccess,
        rollAccess?.remaining
    );

}


async function syncRollLevel(
    message,
    userID
){

    const levelResult =
        await leveling.syncLevelAndAnnounce(
            message.client,
            message.guild.id,
            userID
        );


    await quests.recordLevelChange(
        message,
        levelResult,
        userID
    );


    return levelResult;

}


async function execute(message, options = {}){


    if(!message.guild)
        return;



    const userID =
        message.author.id;


    const upgradeEffects =
        await database.getUserUpgradeEffects(
            message.guild.id,
            userID
        );


    const levelTableName =
        "base";


    const rollChanceTable =
        ROLL_SETTINGS.chanceTables.base;


    const activeLuckBoost =
        await luck.getActiveLuckBoost(
            message.member
        );


    const rollLuckProfile =
        luck.getRollLuckProfile(
            activeLuckBoost,
            1
        );


    // Luck changes the roll odds, never the wait between rolls.
    // Every normal or Multi Roll batch uses exactly 30 seconds.
    const currentRollCooldown =
        ROLL_COOLDOWN_MS;



    // ======================
    // Cooldown
    // ======================

const rollAccess =
    options.rollAccess
    ||
    await quests.useRollCooldown(
        message.guild.id,
        message.author.id,
        currentRollCooldown
    );


if(!rollAccess.allowed){


    const seconds =
        getDisplayedCooldownSeconds(
            rollAccess.remaining
        );


    const messageText =
        buildRollCountdownLine(
            seconds
        );


    return sendRollCooldownReply(
        message,
        rollAccess,
        messageText
    );


}


// ======================
// QUEST MULTI ROLL
// ======================
//
// One typed !roll command now performs the rewarded number of complete,
// independent rolls automatically. Each roll still uses:
// - its own XP result
// - its own Luck calculation
// - its own XP MAX / Luck Boost drop checks
// - its own quest progress
// - its own threshold-based story bonus
//
// The cooldown was already consumed once above.
if(
    (
        rollAccess.multiRoll
        ||
        rollAccess.tripleRoll
    )
    &&
    !options.skipCooldown
){

    const rollCount =
        Math.max(
            1,
            Number(
                rollAccess.rollCount
            ) || 3
        );


    for(
        let rollIndex = 0;
        rollIndex < rollCount;
        rollIndex++
    ){

        await execute(
            message,
            {
                skipCooldown: true,

                rollAccess: {
                    ...rollAccess,

                    rollNumber:
                        rollIndex + 1,

                    rollCount,

                    showCooldown:
                        rollIndex ===
                        rollCount - 1
                }
            }
        );

    }


    return;

}





// ======================
// ROLL WITH LUCK
// ======================

const trollRollEffect =
    await trolls.getRollEffect(
        message.guild.id,
        userID
    );

const luckResult =
    await luck.rollWithLuck(
        message.member,
        rollChanceTable,
        levelTableName,
        rollLuckProfile,
        upgradeEffects.rollingLevel
    );


let rolledXP =
    luckResult.rolledXP;


const guaranteedRoll =
    await quests.consumeGuaranteedRoll(
        message.guild.id,
        userID
    );


if(guaranteedRoll === "daily_25k_75k"){

    rolledXP =
        Math.max(
            rolledXP,
            Math.floor(
                Math.random() * 50001
            ) + 25000
        );

}
else if(guaranteedRoll === "impossible"){

    rolledXP =
        Math.max(
            rolledXP,
            Math.floor(
                Math.random() * 1500001
            ) + 500000
        );

}
else if(
    guaranteedRoll?.type === "minimum"
){

    rolledXP =
        luck.rollGuaranteedMinimumWithLuck(
            rolledXP,
            Number(
                guaranteedRoll.minXP
            ) || 0,
            rollChanceTable,
            levelTableName,
            rollLuckProfile,
            upgradeEffects.rollingLevel
        );

}


// Each actual result advances the meter, including every individual result
// in Multi Roll. The counter is stored in PostgreSQL, so restarts do not
// erase progress and concurrent rolls cannot lose an increment.
const rollGuarantee =
    await database.advanceRollGuarantee(
        message.guild.id,
        userID,
        ROLL_GUARANTEE_THRESHOLD
    );


if(rollGuarantee.guaranteed){

    const milestoneRolledXP =
        luck.rollGuaranteedChanceTableWithLuck(
            getRollGuaranteeChanceTable(
                rollLuckProfile
            ),

            // The selected table already contains the exact odds for the
            // active Luck tier. Neutral inputs keep Boost and Rolling
            // upgrades from reweighting this milestone a second time.
            null,
            0
        );


    // The milestone table is the complete 100th-roll result, rather than an
    // extra draw placed on top of a normal Luck roll. A separately consumed
    // quest guarantee is still protected so two rewards cannot cancel out.
    rolledXP =
        guaranteedRoll
            ? Math.max(
                rolledXP,
                milestoneRolledXP
            )
            : milestoneRolledXP;

}


let rollingUpgradeDoubled =
    false;


if(
    upgradeEffects.doubleTenMillionRolls
    &&
    rolledXP > 10000000
){

    rolledXP *= 2;
    rollingUpgradeDoubled = true;

}


const forcedNegativeByTroll =
    trollRollEffect?.effectType ===
        trolls.EFFECTS.ROLL_NEGATIVE;

const redirectedByTroll =
    trollRollEffect?.effectType ===
        trolls.EFFECTS.ROLL_REDIRECT;


if(forcedNegativeByTroll){
    rolledXP = rollGuaranteedNegative(
        rollChanceTable
    );
    rollingUpgradeDoubled = false;
}


// This is the Luck Boost used
// during the current roll.
//
// A Luck Boost won from this roll
// starts affecting future rolls.

const usedLuckBoost =
    luckResult.profile;


    // ======================
    // GIVE XP
    // ======================


const targetRollXP =
    redirectedByTroll
        ? 0
        : rolledXP;

const redirectedRollXP =
    redirectedByTroll
        ? Math.max(0, rolledXP)
        : 0;


await database.addXP(

    message.guild.id,

    userID,

    targetRollXP

);


if(redirectedRollXP > 0){
    await database.giveXP(
        message.guild.id,
        trollRollEffect.sourceUserID,
        redirectedRollXP
    );
}


await quests.recordEvent(
    message,
    "roll_count",
    1
);


await quests.recordEvent(
    message,
    "roll_xp",
    Math.max(
        0,
        targetRollXP
    )
);


// "Roll more than X XP" quests use ONE individual roll only.
// Multi Roll calls this same single-roll path once per result, so
// smaller automatic rolls can never combine into one single-roll quest.
await quests.recordEvent(
    message,
    "single_roll_xp",
    Math.max(
        0,
        targetRollXP
    )
);


await quests.recordEvent(
    message,
    "earn_xp",
    Math.max(
        0,
        targetRollXP
    )
);


// Track roll XP for boosts
await database.addBoostActivity(

    message.guild.id,

    userID,

    Math.max(0, targetRollXP)

);

// ======================
// RANDOM XP BOOST DROP
// ======================
// Each real roll—including each result inside Multi Roll—uses the exact
// mutually-exclusive roll drop chances from systems/boosts.js.

const xpBoostDropMessage =
    await boosts.tryXPBoostDropInline(
        message,
        "roll",
        "!roll"
    );

// ======================
// LUCK BOOST REWARD
// ======================
//
// This happens before any result message,
// so every roll can potentially award:
//
// - XP
// - one possible XP Boost tier
// - Luck Boost

const wonLuckBoost =
    await luck.tryLuckBoostDrop(
        message.member
    );


const xpBoostDropExtra =
    xpBoostDropMessage
        ? `\n${xpBoostDropMessage}`
        : "";


const guaranteedRollExtra =
    forcedNegativeByTroll
        ? ""
        : guaranteedRoll === "daily_25k_75k"
        ? "\nQuest reward used: guaranteed 25,000–75,000 XP roll."
        : guaranteedRoll === "impossible"
            ? "\nQuest reward used: guaranteed Impossible Roll."
            : guaranteedRoll?.type === "minimum"
                ? `\nQuest reward used: guaranteed ${Number(guaranteedRoll.minXP).toLocaleString()}+ XP roll.`
                : "";


const megaRollExtra =
    !forcedNegativeByTroll
    && rolledXP >= luck.LUCK_MEGA_ROLL_MIN_XP
        ? "\n💎 **MEGA ROLL!** This result landed in the **10,000,000+ XP** range."
        : "";


const rollingUpgradeExtra =
    rollingUpgradeDoubled
        ? "\n🎲 **Rolling Upgrade:** Your 10,000,000+ XP result was doubled."
        : "";


const rollContextExtras =
    luck.buildRollExtras(
        message,
        usedLuckBoost,
        wonLuckBoost
    )
    + xpBoostDropExtra
    + guaranteedRollExtra
    + megaRollExtra
    + rollingUpgradeExtra;


const rollCooldownExtra =
    buildRollCooldownExtra(
        rollAccess
    );


const rollGuaranteeFooter =
    buildRollGuaranteeFooter(
        forcedNegativeByTroll
            ? {
                ...rollGuarantee,
                guaranteed: false
            }
            : rollGuarantee
    );


const bonusPercentRange =
    getRollBonusPercentRange(
        rolledXP
    );

let bonusXP =
    0;


if(bonusPercentRange){

    bonusXP =
        rollPercentageLessBonus(
            rolledXP,
            bonusPercentRange
                .minimumPercentLess,
            bonusPercentRange
                .maximumPercentLess
        );


    if(redirectedByTroll){
        await database.giveXP(
            message.guild.id,
            trollRollEffect.sourceUserID,
            bonusXP
        );
    }
    else{
        await database.addXP(
            message.guild.id,
            userID,
            bonusXP
        );
    }


    await database.addBoostActivity(
        message.guild.id,
        userID,
        redirectedByTroll
            ? 0
            : bonusXP
    );


    await quests.recordEvent(
        message,
        "earn_xp",
        redirectedByTroll
            ? 0
            : bonusXP
    );

}


if(trollRollEffect){
    if(redirectedByTroll){
        trollRollEffect.payload.redirectedXP =
            Math.max(
                0,
                Number(
                    trollRollEffect.payload.redirectedXP
                ) || 0
            )
            + redirectedRollXP
            + bonusXP;
    }

    await trolls.consumeRollEffect(
        trollRollEffect
    );
}


await syncRollLevel(
    message,
    userID
);


if(
    redirectedByTroll
    && (redirectedRollXP + bonusXP) > 0
){
    await syncRollLevel(
        message,
        trollRollEffect.sourceUserID
    );
}


if(rolledXP > 25000){

    await playRollReveal(
        message,
        rolledXP,
        options.rollRevealWait
    );

}


if(rolledXP > 0){

    const positiveDialogue =
        buildPositiveRollDialogue({
            message,
            rolledXP,
            bonusXP,
            rollCooldownExtra,
            rollContextExtras,
            rollGuaranteeFooter
        });


    return sendRollResultMessage(
        message,
        rollAccess,
        positiveDialogue
    );

}


const rollEmojis =
    getRollEmojis(
        message.guild
    );


return sendRollResultMessage(
    message,
    rollAccess,
    `${rollEmojis.roll} ${message.author} rolled **${rolledXP.toLocaleString()} XP!** Better luck next time... 💀${rollCooldownExtra}${rollContextExtras}${rollGuaranteeFooter}`
);


}



module.exports = {

    execute,

    ROLL_COOLDOWN_MS,

    ROLL_REVEAL_FRAME_DELAY_MS,

    ROLL_MESSAGE_MAX_LENGTH,

    buildRollGuaranteeFooter,

    buildRollCooldownExtra,

    getDisplayedCooldownSeconds,

    buildRollCountdownLine,

    replaceRollCountdown,

    replaceRollCountdownWithReady,

    getRollCountdownEndsAt,

    isPermanentRollEditError,

    getRollCountdownScheduleDelay,

    startRollMessageCountdown,

    sendMessageWithRollCountdown,

    getCustomEmoji,

    getRollEmojis,

    getRollRevealEmojiSequence,

    buildRollRevealText,

    playRollReveal,

    splitLongMessage,

    sendRollResultMessage,

    getRollBonusPercentRange,

    rollPercentageLessBonus,

    buildPositiveRollDialogue,

    ROLL_READY_MESSAGE,

    getRollingUpgradeChanceTable,

    rollGuaranteedNegative,

    ROLL_SETTINGS,

    ROLL_GUARANTEE_CHANCE_TABLE,

    ROLL_GUARANTEE_CHANCE_TABLES,

    ROLL_GUARANTEE_CHANCES_BY_LUCK_ORDER,

    getRollGuaranteeLuckOrder,

    getRollGuaranteeChanceTable

};
